namespace ParentalTrack.Domain.Entities;

/// <summary>
/// A child's phone enrolled against a parent account. Created by the parent (which mints a pairing
/// code) and claimed by the app at enrollment. Maps to table <c>child_devices</c>.
/// </summary>
public sealed class ChildDevice
{
    /// <summary>Primary key.</summary>
    public Guid Id { get; set; }

    /// <summary>Owning parent. Cascade delete.</summary>
    public Guid ParentId { get; set; }

    /// <summary>Name of the child, shown throughout the admin UI.</summary>
    public string ChildName { get; set; } = string.Empty;

    /// <summary>Parent-chosen label for the handset, e.g. "Sam's phone".</summary>
    public string? DeviceLabel { get; set; }

    /// <summary>Platform reported at enrollment, e.g. "android".</summary>
    public string? Platform { get; set; }

    /// <summary>Hardware manufacturer reported at enrollment.</summary>
    public string? Manufacturer { get; set; }

    /// <summary>Hardware model reported at enrollment.</summary>
    public string? Model { get; set; }

    /// <summary>Operating system version reported at enrollment.</summary>
    public string? OsVersion { get; set; }

    /// <summary>Child app version reported at enrollment.</summary>
    public string? AppVersion { get; set; }

    /// <summary>Random identifier generated by the app on first run.</summary>
    public string? InstallId { get; set; }

    /// <summary>SHA-256 (base64) of the pairing code. Cleared once the code is consumed.</summary>
    public string? PairingCodeHash { get; set; }

    /// <summary>Expiry of the outstanding pairing code.</summary>
    public DateTimeOffset? PairingCodeExpiresAt { get; set; }

    /// <summary>When the device completed enrollment. Null means it was never enrolled.</summary>
    public DateTimeOffset? PairedAt { get; set; }

    /// <summary>False soft-disables the device: its tokens stop validating and ingestion is refused.</summary>
    public bool IsActive { get; set; } = true;

    /// <summary>When the device row was created by the parent.</summary>
    public DateTimeOffset CreatedAt { get; set; }

    /// <summary>Greatest accepted <c>recordedAt</c>; drives the status/staleness calculation.</summary>
    public DateTimeOffset? LastSeenAt { get; set; }

    /// <summary>Battery level from the newest accepted fix.</summary>
    public int? LastBatteryPercent { get; set; }

    /// <summary>
    /// Denormalised pointer to the newest <c>location_records</c> row. Deliberately a plain indexed
    /// column with no foreign key, so retention deletes never have to fix it up.
    /// </summary>
    public long? LastLocationId { get; set; }
}
