#!/usr/bin/env bash
#
# ParentalTrack — one-time privileged server setup for parent.flexypdf.com
#
#   sudo bash deploy/server-setup.sh
#
# This box hosts many other production sites, so the script is deliberately conservative:
#   * it only CREATES things, never edits or deletes anything that already exists;
#   * every step is idempotent — running it twice changes nothing the second time;
#   * it validates the nginx config before reloading, and refuses to reload a broken one.
#
# What it does:
#   1. PostgreSQL role + database  (parentaltrack)
#   2. /etc/parentaltrack/parentaltrack-api.env  with generated secrets, root-only
#   3. systemd unit                (parentaltrack-api.service)
#   4. sudoers drop-in             so deploys can restart the service without a password
#   5. nginx vhost                 (HTTP only — certbot adds TLS afterwards)
#
set -euo pipefail

DOMAIN="parent.flexypdf.com"
APP_USER="flexyuser"
APP_PORT="5090"
APP_ROOT="/home/${APP_USER}/${DOMAIN}"
DB_NAME="parentaltrack"
DB_USER="parentaltrack"
DB_HOST="127.0.0.1"
DB_PORT="5432"
ENV_DIR="/etc/parentaltrack"
ENV_FILE="${ENV_DIR}/parentaltrack-api.env"
SERVICE="parentaltrack-api"

# Bootstrap administrator for the admin panel. Change ADMIN_EMAIL before running if you want a
# different login; the password is generated and printed once at the end.
ADMIN_EMAIL="${ADMIN_EMAIL:-kishan@devswifter.com}"
ADMIN_NAME="${ADMIN_NAME:-Kishan}"

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [[ "${EUID}" -ne 0 ]]; then
  echo "This script must run as root:  sudo bash deploy/server-setup.sh" >&2
  exit 1
fi

say() { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }
ok()  { printf '    \033[0;32m%s\033[0m\n' "$*"; }
note(){ printf '    %s\n' "$*"; }

# ---------------------------------------------------------------------------------------------
say "1/5  PostgreSQL role and database"

role_exists=$(sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='${DB_USER}'" || true)
db_exists=$(sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}'" || true)

if [[ "${role_exists}" == "1" ]]; then
  ok "role '${DB_USER}' already exists — leaving its password untouched"
  DB_PASSWORD=""
else
  DB_PASSWORD="$(openssl rand -base64 24 | tr -d '/+=' | cut -c1-28)"
  sudo -u postgres psql -c "CREATE ROLE ${DB_USER} LOGIN PASSWORD '${DB_PASSWORD}';" >/dev/null
  ok "created role '${DB_USER}'"
fi

if [[ "${db_exists}" == "1" ]]; then
  ok "database '${DB_NAME}' already exists"
else
  sudo -u postgres psql -c "CREATE DATABASE ${DB_NAME} OWNER ${DB_USER};" >/dev/null
  ok "created database '${DB_NAME}' owned by ${DB_USER}"
fi

# ---------------------------------------------------------------------------------------------
say "2/5  Secrets file  ${ENV_FILE}"

install -d -m 0750 -o root -g "${APP_USER}" "${ENV_DIR}"

if [[ -f "${ENV_FILE}" ]]; then
  ok "already exists — keeping the existing secrets"
  ADMIN_PASSWORD="(unchanged — see ${ENV_FILE})"
else
  if [[ -z "${DB_PASSWORD}" ]]; then
    echo "The '${DB_USER}' role already existed but ${ENV_FILE} does not, so its password is unknown." >&2
    echo "Reset it and re-run:  sudo -u postgres psql -c \"ALTER ROLE ${DB_USER} PASSWORD 'new-password';\"" >&2
    echo "then create ${ENV_FILE} by hand from deploy/parentaltrack-api.env.example." >&2
    exit 1
  fi

  JWT_KEY="$(openssl rand -base64 64 | tr -d '\n')"
  ADMIN_PASSWORD="$(openssl rand -base64 18 | tr -d '/+=' | cut -c1-20)"

  umask 077
  cat > "${ENV_FILE}" <<ENVEOF
# ParentalTrack API — generated by deploy/server-setup.sh. Root-readable only.
ASPNETCORE_ENVIRONMENT=Production
ASPNETCORE_URLS=http://127.0.0.1:${APP_PORT}
DOTNET_PRINT_TELEMETRY_MESSAGE=false

ConnectionStrings__Postgres=Host=${DB_HOST};Port=${DB_PORT};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}

# Signing key for both parent and device JWTs. Rotating it signs every parent and every child
# device out at once, which is the intended break-glass action.
Jwt__SigningKey=${JWT_KEY}

Cors__AllowedOrigins__0=https://${DOMAIN}

# Bootstrap administrator. The seeder is idempotent: it creates this account on an empty database
# and does nothing on every later start. Safe to leave enabled.
Seed__Enabled=true
Seed__ParentEmail=${ADMIN_EMAIL}
Seed__ParentPassword=${ADMIN_PASSWORD}
Seed__ParentDisplayName=${ADMIN_NAME}

# Standard libpq variables, so deploy.sh can apply migrations with psql without re-parsing the
# connection string. The application ignores these.
PGHOST=${DB_HOST}
PGPORT=${DB_PORT}
PGDATABASE=${DB_NAME}
PGUSER=${DB_USER}
PGPASSWORD=${DB_PASSWORD}
ENVEOF
  # Readable by the service account, which already receives these values in its process environment
  # at runtime — so 0640 grants nothing it did not effectively have, and lets deploys run migrations.
  chown root:"${APP_USER}" "${ENV_FILE}"
  chmod 0640 "${ENV_FILE}"
  ok "created with generated database password, JWT key and admin password"
fi

# ---------------------------------------------------------------------------------------------
say "3/5  Application directory and systemd unit"

install -d -m 0755 -o "${APP_USER}" -g "${APP_USER}" "${APP_ROOT}" "${APP_ROOT}/current"
ok "${APP_ROOT}/current ready"

install -m 0644 "${HERE}/systemd/${SERVICE}.service" "/etc/systemd/system/${SERVICE}.service"
systemctl daemon-reload
systemctl enable "${SERVICE}" >/dev/null 2>&1 || true
ok "installed and enabled ${SERVICE}.service (not started — deploy.sh starts it)"

# ---------------------------------------------------------------------------------------------
say "4/5  Password-less service control for ${APP_USER}"

SUDOERS="/etc/sudoers.d/parentaltrack"
SYSTEMCTL="$(command -v systemctl)"
cat > "${SUDOERS}.tmp" <<SUDOEOF
# Lets deploy.sh restart only this one service without a password. Nothing else is granted.
${APP_USER} ALL=(root) NOPASSWD: ${SYSTEMCTL} start ${SERVICE}, ${SYSTEMCTL} stop ${SERVICE}, ${SYSTEMCTL} restart ${SERVICE}, ${SYSTEMCTL} status ${SERVICE}, ${SYSTEMCTL} is-active ${SERVICE}
SUDOEOF
chmod 0440 "${SUDOERS}.tmp"
# visudo -c validates before the file goes live; a malformed sudoers file locks everyone out.
if visudo -cf "${SUDOERS}.tmp" >/dev/null; then
  mv "${SUDOERS}.tmp" "${SUDOERS}"
  ok "installed ${SUDOERS}"
else
  rm -f "${SUDOERS}.tmp"
  echo "sudoers snippet failed validation — skipped. Deploys will prompt for a password." >&2
fi

# ---------------------------------------------------------------------------------------------
say "5/5  nginx vhost"

NGINX_AVAILABLE="/etc/nginx/sites-available/${DOMAIN}"
NGINX_ENABLED="/etc/nginx/sites-enabled/${DOMAIN}"

if [[ -f "${NGINX_AVAILABLE}" ]]; then
  ok "${NGINX_AVAILABLE} already exists — left untouched (certbot may have edited it)"
else
  install -m 0644 "${HERE}/nginx/${DOMAIN}.conf" "${NGINX_AVAILABLE}"
  ok "installed ${NGINX_AVAILABLE}"
fi

[[ -L "${NGINX_ENABLED}" ]] || ln -s "${NGINX_AVAILABLE}" "${NGINX_ENABLED}"

if nginx -t; then
  systemctl reload nginx
  ok "nginx reloaded"
else
  echo "nginx config test FAILED — not reloading. Existing sites are unaffected." >&2
  exit 1
fi

# ---------------------------------------------------------------------------------------------
cat <<SUMMARY

$(printf '\033[1;32m')Server setup complete.$(printf '\033[0m')

  Database   ${DB_NAME} on ${DB_HOST}:${DB_PORT}, owner ${DB_USER}
  Secrets    ${ENV_FILE}  (root, 0600)
  Service    ${SERVICE}.service  ->  127.0.0.1:${APP_PORT}
  App dir    ${APP_ROOT}/current
  Vhost      ${DOMAIN}  (HTTP only so far)

  Admin login for https://${DOMAIN}
     email     ${ADMIN_EMAIL}
     password  ${ADMIN_PASSWORD}
  Save that password now — it is stored only in ${ENV_FILE}.

Next, from your workstation:
  1.  bash deploy/deploy.sh          # build, upload, migrate, start
  2.  sudo certbot --nginx -d ${DOMAIN}    # issue the TLS certificate

SUMMARY
